### ISSUE TITLE
netplan issues on home server

### ISSUE THREAD

**Issue by sbates130272** [sbates130272/batesste-ansible#26]
Since my home server has a bunch of network interfaces the boot stalls on waitng for IP address. Need to use netplan to make interfaces optional. See [this][ref] for some discussion. Also got something that might be close to working:
```
batesste@newry:~$ cat /etc/netplan/02-ignore-newry-unused-interfaces.yml
# Written by batesste on 14 Oct 2022 for newry
network:
  version: 2
  ethernets:
    wlp7s0:
      optional: true
    enp7s0:
      optional: true
```

[ref]: https://askubuntu.com/questions/972215/a-start-job-is-running-for-wait-for-network-to-be-configured-ubuntu-server-17-1

**Comment by sbates130272** [comment]
This also seems to be related. Note the above is not consistently working for some reason.

```
systemd-networkd-wait-online.service
```

**Comment by sbates130272** [comment]
Oh the reason this script in the first comment does not work consistently is that the damn interface names can change from one install of the OS to another.

**Comment by sbates130272** [comment]
Using [this][ref1] and setting its status to ```--any``` may work better.

[ref1]: https://man7.org/linux/man-pages/man8/systemd-networkd-wait-online.service.8.html

**Comment by sbates130272** [comment]
So a nice way to solve this is to add the --any command option to the call into the systemd-networkd-wait-online. This is a nice thing to do on any system so I may well implement a role for this.

```
ExecStart=/lib/systemd/systemd-networkd-wait-online --any
```

**Comment by sbates130272** [comment]
Turns out that ```--any``` does have issues when we add virtualization because it includes things like virtual NICs and bridges. So we may need a better approach.

Locking interface names to MAC addresses might work well on certain machines like [this][1]. Re-opening.

[1]: https://askubuntu.com/questions/1255823/network-interface-names-change-every-reboot

**Comment by sbates130272** [comment]
What works well on Newry is a combination of this:

```
#  SPDX-License-Identifier: LGPL-2.1-or-later
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Wait for Network to be Configured
Documentation=man:systemd-networkd-wait-online.service(8)
DefaultDependencies=no
Conflicts=shutdown.target
Requires=systemd-networkd.service
After=systemd-networkd.service
Before=network-online.target shutdown.target

[Service]
Type=oneshot
ExecStart=/lib/systemd/systemd-networkd-wait-online --interface=enp1s0
RemainAfterExit=yes

[Install]
WantedBy=network-online.target
```
and this
```
# This is the network config written by 'subiquity'
network:
  ethernets:
    enp1s0:
      match:
        macaddress: 58:11:22:b0:56:50
      dhcp4: true
      set-name: enp1s0
    enp2s0:
      match:
        macaddress: 58:11:22:b0:56:51
      set-name: enp2s0
      dhcp4: true
      optional: true
  version: 2
```
